added seasonal artifact display enhancements
DestinyItemManager/DIM pull request #10200
Opened 2023-12-27 21:35 UTC by mjlemay

In support of https://github.com/DestinyItemManager/DIM/issues/8716

2023-12-27 21:46 UTC, delphiactual commented on src/app/vendors/single-vendor/ArtifactUnlocks.tsx
> +        <div>{t('Progress.Resets_plural', { count: resetCount })}</div>
```suggestion
        <div>{t('Progress.PointsUsed', { count: pointsUsed })}</div>
        <div>{t('Progress.Resets', { count: resetCount })}</div>
```

2023-12-27 21:48 UTC, delphiactual commented on package-lock.json
we are no longer using `yarn` please remove and do a `pnpm install`

2023-12-27 22:06 UTC, delphiactual commented
did you rerun `pnpm i18n`?

2023-12-27 22:15 UTC, delphiactual requested changes

2023-12-27 22:15 UTC, delphiactual commented on config/i18n.json
> +    "PointsUsed_plural": "{{count}} points used",
```suggestion
    "PointsUsed": "1 point used",
    "PointsUsed_plural": "{{count}} points used",
```

2023-12-27 22:36 UTC, delphiactual approved these changes

2023-12-27 22:58 UTC, delphiactual commented
![image](https://github.com/DestinyItemManager/DIM/assets/4798491/81f8cb1c-fedb-4e32-bbfe-3192fd474691)

2023-12-28 02:45 UTC, bhollis commented
@delphiactual thanks for adding screenshots. @mjlemay would you mind updating the PR description to describe what you've changed?

2023-12-28 18:53 UTC, nev-r approved these changes

2023-12-28 23:11 UTC, bhollis approved these changes
Thanks!

2023-12-28 23:12 UTC, merged