Add `deepsight:harmonizable` filter and deepsight-related Organizer columns
DestinyItemManager/DIM pull request #10354
Opened 2024-04-23 00:59 UTC by bjacobel

Refs https://github.com/DestinyItemManager/DIM/issues/10184

Adds:
* An organizer column for "Deepsight level" (ie: crafted weapon level)
    ![image](https://github.com/DestinyItemManager/DIM/assets/407639/1c51f335-60d3-43b6-9f28-334b3a75be20)
* An Organizer column for "Deepsight harmonizable" (ie: can a Harmonizer be used to extract Deepsight crafting progress)
    ![image](https://github.com/DestinyItemManager/DIM/assets/407639/b1807cd5-f0d5-47c1-876e-73199847690c)
* A `deepsight:harmonizable` query filter
  <img width="1050" alt="image" src="https://github.com/DestinyItemManager/DIM/assets/407639/b85b43ca-4ec4-4042-9c2a-c1a4c4882e0b">

Let me know if there's manual work that needs doing for the new i18n entries? I wasn't sure how that stuff works.

2024-04-23 01:06 UTC, bjacobel commented
Just realizing now that my branch was _way_ out of date, will need a little time to rebase this...

2024-04-25 04:46 UTC, bhollis requested changes
Thanks! Left some comments about changes that are required before merging.

2024-04-25 04:46 UTC, bhollis commented on config/i18n.json
> +      "DeepsightLevel": "Deepsight Level",
This could be just "Level", since there aren't other types of Level for weapons (so far)

2024-04-25 04:46 UTC, bhollis commented on config/i18n.json
> +      "DeepsightHarmonizable": "Deepsight Harmonizable",
This could be "Harmonizable" to save space

2024-04-25 04:46 UTC, bhollis commented on config/i18n.json
> +    "No": "No"
For other boolean columns (e.g. sunset) we use a check icon or nothing, not yes and no.

2024-04-25 04:46 UTC, bhollis commented on src/app/organizer/Columns.tsx
> +        value: (item) => (isHarmonizable(item) ? t('Organizer.Yes') : t('Organizer.No')),
The value should be the boolean (true or false) and then the cell should be the actual content.

2024-04-27 01:00 UTC, bjacobel commented
Thanks for the review! Those changes should be ready:

<img width="864" alt="image" src="https://github.com/DestinyItemManager/DIM/assets/407639/170af70a-dd8f-4ad9-acfb-f89d0c9b13ef">

2024-04-27 04:42 UTC, bhollis approved these changes

2024-04-27 04:42 UTC, merged