DIM-6473: fix message for untransferable Postmaster items
DestinyItemManager/DIM pull request #6477
Opened 2021-01-30 18:13 UTC by goomba5

2021-01-30 19:57 UTC, bhollis requested changes

2021-01-30 19:57 UTC, bhollis commented on src/app/inventory/DraggableInventoryItem.tsx
> +  const stores = useSelector(sortedStoresSelector);
This makes sense, but we shouldn't add redux subscriptions to this component - it'd slow down DIM. We may have to find another way to do this that doesn't require looking at stores.

2021-01-30 19:57 UTC, bhollis commented on src/app/item-popup/ItemPopupBody.tsx
> +  const stores = useSelector(sortedStoresSelector);
No need to use the sorted stores selector, can use regular stores

2021-01-30 19:57 UTC, bhollis commented on src/app/item-popup/ItemPopupBody.tsx
> +  if (!store) {
Not all items are owned by a character - this will likely break vendor items.

2021-01-30 23:41 UTC, bhollis commented
Some things to consider:

1. The original logic for showing the banner was probably OK, so we can go back to that. 
2. If you need Redux state for the item, ConnectedInventoryItem is the one place we have a subscription. 
3. We need to make sure the popup still works on the Vendors screen and the Progress screen. 

Since DIM automatically releases to production on Sunday afternoons, I'll probably revery your original change sometime between now and then to prevent it from going out, then we can take another pass at it.

2021-01-31 01:36 UTC, goomba5 commented
I appreciate the feedback and honesty. I'll keep an eye out for another ticket to work on.

2021-01-31 23:05 UTC, closed without merging