Properly describe the thing being inserted or selected by SocketDetails popup
DestinyItemManager/DIM pull request #7559
Opened 2021-12-26 18:07 UTC by robojumper

After changing it for shaders and ornaments, I realized that `SocketDetailsSelectedPlug` is responsible for quite a few more kinds of items. This adds the rest of the names for kinds of plugs.

2021-12-26 18:08 UTC, robojumper commented
This is the first time I'm interacting with the `i18next-scanner`, so I'm not sure if this is the preferred approach, cc @delphiactual.
Also not too sure about the "Insert/Apply/Equip" wording -- I used "Apply" where there's always only one of those slots on the item, "Insert" for multiple equivalent sockets, and "Equip" for the ability sockets.

2021-12-27 20:36 UTC, delphiactual requested changes

2021-12-27 20:36 UTC, delphiactual commented on config/i18n.json
> +    "SelectProjection": "Select Ghost Projection",
```suggestion
    "Insert":  {
        "Mod": "Insert Mod",
        etc...
     }
    "Select": {
         "Mod": "Select Mod",
         etc....
    }
```

2021-12-27 20:36 UTC, delphiactual commented on src/app/item-popup/SocketDetailsSelectedPlug.tsx
> +  // t(`Sockets.Select`, { contextList: 'sockets' })
remove

2021-12-27 20:36 UTC, delphiactual commented on src/locale/dim.json
> +    "SelectTransmat": "Select Transmat Effect",
same as config/i18n.json

2021-12-27 20:48 UTC, robojumper commented
Thanks @delphiactual, I think I've addressed these.

2021-12-27 20:53 UTC, delphiactual approved these changes

2021-12-28 19:28 UTC, merged