Support comments in searches
DestinyItemManager/DIM pull request #8205
Opened 2022-03-20 23:44 UTC by bhollis

Fixes #7174 to the extent I want to fix it.

This allows for single-line comments of the form `/* A comment */` in searches. When canonicalizing, all but the top-level comment will be removed, but the top level comment will always be in front. This is mostly an alternative to doing `name:"My cool search" or ...`

2022-03-20 23:49 UTC, bhollis commented
Oh also - as part of this I stopped lowercasing the whole filter. I think this is OK? It's kinda weird that it was always lowercased before.

2022-03-21 00:00 UTC, robojumper requested changes
The case change makes things hairy.

Actual parsing and interpretation lowercases anyway, so it keeps working:

https://github.com/DestinyItemManager/DIM/blob/44e6550aacfd6d643edd2838e9a38ca1e00f7d0f/src/app/search/search-filter.ts#L107-L114

but validation doesn't, and as a result of this

https://github.com/DestinyItemManager/DIM/blob/44e6550aacfd6d643edd2838e9a38ca1e00f7d0f/src/app/search/query-parser.ts#L265-L266

validation parses all uppercase filters as bare keyword filters (e.g. the whole `SeASon:worthy` becomes a keyword).

2022-03-21 00:18 UTC, bhollis commented
Gotcha yeah - I was hoping we didn't have filter usage where the keyword itself wasn't already lowercase, but that's easy enough to force.

2022-03-21 08:31 UTC, robojumper approved these changes

2022-03-24 20:26 UTC, merged