https://github.com/DestinyItemManager/DIM/issues/8664
DestinyItemManager/DIM pull request #8699
Opened 2022-09-11 16:58 UTC by trevor-sutherland

[…estinyItemManager/DIM/issues/8664](https://github.com/DestinyItemManager/DIM/issues/8664)

2022-09-11 17:04 UTC, delphiactual commented on src/app/inventory/store/energy.ts
> +  tierSocket = armorTierSocket;
```suggestion
  const tierSocket = armorTierSocket?.plugSet ? armorTierSocket : ghostTierSocket;
```

2022-09-11 18:56 UTC, delphiactual approved these changes

2022-09-11 18:56 UTC, delphiactual commented on src/app/inventory/store/energy.ts
> +  let tierSocket;
remove

2022-09-11 18:56 UTC, delphiactual commented on src/app/inventory/store/energy.ts
> +  }
remove

2022-09-11 23:31 UTC, delphiactual commented
```
  const tierSocket =
    item.sockets &&
    (getFirstSocketByCategoryHash(item.sockets, SocketCategoryHashes.ArmorTier) ||
      getFirstSocketByCategoryHash(item.sockets, SocketCategoryHashes.GhostTier));
```

2022-09-12 14:52 UTC, delphiactual requested changes

2022-09-12 14:52 UTC, delphiactual commented on src/app/inventory/store/energy.ts
> +  let tierSocket;
```suggestion
  const tierSocket =
    item.sockets &&
    (getFirstSocketByCategoryHash(item.sockets, SocketCategoryHashes.ArmorTier) ||
      getFirstSocketByCategoryHash(item.sockets, SocketCategoryHashes.GhostTier));
```

2022-09-12 14:52 UTC, delphiactual commented on src/app/inventory/store/energy.ts
> +  const armorTierSocket =
remove

2022-09-12 14:52 UTC, delphiactual commented on src/app/inventory/store/energy.ts
> +  }
remove

2022-09-12 21:42 UTC, delphiactual requested changes

2022-09-12 21:42 UTC, delphiactual commented on src/app/item-popup/EnergyMeter.tsx
> +  ) {
```suggestion
  // return null if not swappable and not a ghost
  if (
    !item.energy ||
    ![...swappableEnergyTypes, DestinyEnergyType.Ghost].includes(item.energy.energyType) {
```

2022-09-12 21:42 UTC, delphiactual commented on src/app/item-popup/EnergyMeter.tsx
> +
remove

2022-09-13 11:30 UTC, delphiactual approved these changes

2022-09-14 02:35 UTC, trevor-sutherland commented on src/app/dim-ui/ConfirmButton.m.scss
> +        background-color: #a22 !important;
My bad, I didn't know how/why I committed that. "yarn fix" addition maybe?

2022-09-16 02:17 UTC, merged