Replace/upgrade virtual scrollers
DestinyItemManager/DIM pull request #9541
Opened 2023-06-04 01:55 UTC by bhollis

1. Replace `react-virtualized` with `@tanstack/react-virtual`. It's a lot smaller and easier to use.
2. Item heights are now computed dynamically, on demand. No more "render an example row". I managed to get this working using `react-virtualized` but `@tanstack/react-virtual` supports it better (it uses resize observers to keep track of sizes if they change). `@tanstack/react-virtual` also uses a technique where it moves along a container item with the windowed rows using `translateY` instead of individually sizing and positioning each item.
3. Apply this, via some common utility components, to LO sets, Loadouts, Item Feed, and even the Inventory screen (too much?). No more managing `itemsToShow` in Item Feed. This work replaces #9512.

On the item feed at least, there is some minor repositioning that's noticeable if you scroll fast enough as the library catches up with measuring each item, but I think it's still nicer than the old method of rendering an ever-increasing list as you scroll. I'd love some testing on other computers/browsers as I rarely experience performance issues.

2023-06-04 02:05 UTC, bhollis commented on src/app/item-feed/ItemFeed.tsx
> -    >
I gave up on having items animate in and out in the item feed. It was fun, but it becomes way more obvious when you're scrolling and items are appearing/disappearing constantly.

2023-06-04 10:02 UTC, robojumper requested changes
1. On Windows 10 Edge and Firefox this breaks drag and drop on the main inventory page.
2. As noted in #9512, this breaks the "click on menu entry to scroll to loadout" behavior on the desktop Loadouts page -- this might need to be wired up with virtual's [scrollToIndex](https://tanstack.com/virtual/v3/docs/api/virtualizer#scrolltoindex)

2023-06-04 10:07 UTC, robojumper commented
Very happy to see the set height measuring code gone. Item Feed feels much snappier now when scrolling quickly.

2023-06-05 00:19 UTC, bhollis commented
OK, I've fixed the Loadouts menu, and I just reverted using this for the Inventory page. My guess is the fact that the elements are now inside a transformed div messes up the drag and drop positioning calculations. Weirdly, drag and drop does still work on the Loadouts screen...

2023-06-05 11:12 UTC, robojumper approved these changes

2023-06-05 20:20 UTC, merged