Use Intl.Collator for searching/sorting loadouts
DestinyItemManager/DIM pull request #9829
Opened 2023-09-02 01:13 UTC by bhollis

This gets us the behavior of loadouts "properly" ordering names with numbers in them. I also made the search use the collator, but that's less of a win - the object doesn't have a substring "includes" method so you have to roll your own. It's actually pretty fast, but I'm not sure I want to go through and replace all our other text searches with it. Part of that is I don't know how badly our current search is failing folks who use languages that actually have accents.

I also fixed the `loadoutsForClassTypeSelector` that @nev-r pointed out.

2023-09-02 14:43 UTC, robojumper requested changes
I'm into it but maybe we can extract `Collator` stuff to separate functions and add some tests?

2023-09-02 14:43 UTC, robojumper commented on src/app/loadout/loadout-ui/menu-hooks.tsx
> +  const filterCollator = new Intl.Collator(language, { usage: 'search', sensitivity: 'base' });
These crash with our `zh-cht` and `zh-chs` languages because browsers expect either `zh` or something like `zh-Hant` and `zh-Hans`.

2023-09-02 14:43 UTC, robojumper commented on src/app/loadout/loadout-ui/menu-hooks.tsx
> +    }
Not 100% sure if that's correct Unicode-aware handling, since this will happily pull apart UTF-16 surrogate pairs.

2023-09-02 17:57 UTC, bhollis commented
Yeah definitely worth extracting/testing especially if we want to use it elsewhere.

2023-09-09 10:55 UTC, robojumper approved these changes

2023-09-09 16:19 UTC, merged