Sheet CSS modules
DestinyItemManager/DIM pull request #9911
Opened 2023-09-23 22:36 UTC by bhollis

Move Sheet CSS to modules, which also solves the specificity problems we've had with them.

2023-09-26 15:20 UTC, robojumper requested changes
Once again seems to break the mobile item popup sheet header 
![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/4ff4a293-a004-4e54-b7bb-23720b9bf154)

2023-09-28 04:03 UTC, bhollis commented
Unfortunate - my intention was actually to fix this sort of specificity problem by flattening the original sheet classes, and then relying on the fact that the sheet classes would appear before the sheet-modifier classes. Unfortunately the styles don't seem to be in import-graph order.

I wish I could use `@layer` but we can't as long as we're stuck with Chrome 85 from Steam.

2023-09-28 04:11 UTC, bhollis commented
I "solved" this by importing the stylesheet directly in `Index.tsx` which makes it load higher up in the overall stylesheet. Someday we'll have `@layer` and can fix this the right way.

2023-09-28 04:12 UTC, bhollis commented on src/app/_variables.scss
> +// Utility functions to allow for augmenting a hex color value with an alpha component.
I snuck this change in here, but as I was debugging I noticed that this big block comment was getting output in every file, which seemed unnecessary.

2023-09-28 12:59 UTC, robojumper approved these changes

2023-09-28 14:35 UTC, merged